[package]
name = "fuel-optimization"
version = "0.1.0"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
edition = "2018"

[dependencies]
csv = "*"
interpolation = "*"
ordered-float = "*"
plotlib = "^0.5.1"
